[advisories]
version = 2
yanked = "deny"
ignore = [
]

[bans]
deny = [
]
multiple-versions = "allow"

[licenses]
version = 2
allow = [
  "Apache-2.0",
  "MIT",
  "ISC",
  "Unicode-DFS-2016",
  "BSD-3-Clause",
]
